= The O64ml Project / _Progetto O64ml_
Piero Furiesi <p.furiesi@tiscali.it>

=== Alpha version
=== Full of bugs - please wait for a stable release

|===
| *OCaml for the Commodore 64* | *_OCaml per il Commodore 64_*

| An OCaml compiler which generates object code targeted for the
  Commodore 64.
| _Un compilatore del linguaggio OCaml che genera codice eseguibile
  per il Commodore 64._

| *Overview* | *_In breve_*

| The O64ml Project allows you to develop OCaml programs and compile
  them on Linux systems to produce code executable on a Commodore 64.
  The Project includes, in addition to the `o64ml` compiler, a specially
  modified distribution of the OCaml Standard Library and (coming
  soon) libraries dedicated to graphics and sound.
| _Il Progetto O64ml consente di sviluppare programmi in OCaml e
  compilarli su sistemi Linux producendo codice eseguibile da un
  Commodore 64. Il Progetto comprende, oltre al compilatore `o64ml`, una
  distribuzione della Standard Library di OCaml appositamente
  modificata e (prossimamente) delle librerie dedicate alla grafica e
  al suono._

| *Installation* | *_Installazione_*

| See link:INSTALL[].
| _Vedere link:INSTALL[] (in inglese)._ 

| *Documentation* | *_Documentazione_*

| The installation procedure generates manual pages for the `o64ml`
  compiler (readable with the `man o64ml` command) and for the StdLib
  modules (`man 3o64 module-name`). Please read also
  link:CAVEATS-LIMITATIONS-NOTES[] and link:BUGS[].

| _La procedura di installazione genera le pagine di manuale per il
  compilatore `o64ml` (leggibile con il comando `man o64ml`) e per i
  moduli della StdLib (`man 3o64 nome-modulo`). Si consiglia di leggere
  link:CAVEATS-LIMITATIONS-NOTES[] e link:BUGS[]._

| *License:* see link:LICENSE-en[] | *_Licenza:_* _vedere link:LICENZA-it[]._
|===
