#!/bin/bash

# -----------------------------------------------------------------------
# Progetto BreadCaml / The BreadCaml Project
# Copyright (C) 2026 Piero Furiesi
#
# Questo  programma  è  software  libero; può  essere  ridistribuito  e/o
# modificato nei termini della GNU  General Public License (GPL) versione
# 2; si veda il file LICENZA-it nella cartella radice del progetto.
#
# This program is free software; you can redistribute it and/or modify it
# under the terms  of the GNU General Public License  (GPL) version 2, as
# specified in the LICENSE-en file in the project root folder.
# -----------------------------------------------------------------------

function help {
    cat <<EOF
$0 [DIRECTORY]
Aggiunge gli header appropriati a tutti i file sorgenti OCaml o ACME
nella DIRECTORY indicata e nelle sue subdirectory.
Se DIRECTORY non è indicata, stampa i modelli di header disponibili.
EOF
}

function print_templates {
    for I in ${!TITLE[@]}; do
	echo
	echo "MODELLO $I) ${TITLE[$I]}"
	echo "${HEADER[$I]}"
	echo
    done | less
}

function ask_user {
    echo "Quale header vuoi applicare ai file in '$DIR'?"
    for I in ${!TITLE[@]}; do
	echo " $I) ${TITLE[$I]}"
    done
    echo "Scegli un'opzione da 1 a ${#TITLE[@]},"
    read -p "oppure 0 per RIMUOVERE tutti gli header: " CHOICE
}

function add_header { #FILE #CHOICE
    # Salta il file se nelle prime tre righe contiene già la firma
    if grep -q -m 3 "$SIGNATURE" "$1"; then
        echo "Saltato (header già presente): $1"
    else
        TEMP_FILE=$(mktemp)
        echo "${HEADER[$2]}" > "$TEMP_FILE"
        echo >> "$TEMP_FILE"
        cat "$1" >> "$TEMP_FILE"
        mv "$TEMP_FILE" "$1"
        echo "Header n° $2 inserito in: $1"
    fi
}


# DATI DESCRITTIVI

DATE="21-Apr-2026"
SIGNATURE="Progetto BreadCaml / The BreadCaml Project"
AUTHOR="Piero Furiesi"


# DEFINIZIONE DEGLI HEADER

TITLE[1]="Sorgenti OCaml - no terze parti (GPL v2)"
FIND[1]='-name "*.ml" -o -name "*.mli" -o -name "*.ml.tpl"'
HEADER[1]=$(cat <<EOF
(* ----------------------------------------------------------------------
   $SIGNATURE
   Copyright (C) $DATE $AUTHOR

   Questo  programma  è software  libero;  può  essere ridistribuito  e/o
   modificato nei termini della GNU General Public License (GPL) versione
   2; si veda il file LICENZA-it nella cartella radice del progetto.

   This program is  free software; you can redistribute  it and/or modify
   it under the terms of the  GNU General Public License (GPL) version 2,
   as specified in the LICENSE-en file in the project root folder.
   ---------------------------------------------------------------------- *)
EOF
)

TITLE[2]="Sorgenti ACME - no terze parti (GPL v2)"
FIND[2]='-name "*.asm"'
HEADER[2]=$(cat <<EOF
;; ----------------------------------------------------------------------
;; $SIGNATURE
;; Copyright (C) $DATE $AUTHOR
;;
;; Questo  programma  è software  libero;  può  essere ridistribuito  e/o
;; modificato nei termini della GNU General Public License (GPL) versione
;; 2; si veda il file LICENZA-it nella cartella radice del progetto.
;;
;; This program is  free software; you can redistribute  it and/or modify
;; it under the terms of the  GNU General Public License (GPL) version 2,
;; as specified in the LICENSE-en file in the project root folder.
;; ----------------------------------------------------------------------
EOF
)

TITLE[3]="StdLib di OCaml modificata (LGPL v2.1 + Eccezione)"
FIND[3]='-name "*.ml" -o -name "*.mli"'
HEADER[3]=$(cat <<EOF
(* ----------------------------------------------------------------------
   $SIGNATURE
                                     SOFTWARE DI TERZI/3RD PARTY SOFTWARE
   OCaml Standard Library
     Origine/Source: https://ocaml.org
     Copyright (C) 1996 Institut National de Recherche en Informatique et
     en Automatique
     Modifiche/Modifications: $DATE $AUTHOR

   Questo file è distribuito nei termini  della licenza LGPL ver. 2.1 con
   le eccezioni riportate nel file LICENSE (in inglese).
   Il codice originale rimosso o sostituito è incluso tra (*-- e --*); le
   aggiunte sono  identificate da  (*++ e ++*)  oppure, nei  commenti per
   OCamldoc, da {i {b BreadCaml Note} ... }.

   This file is distributed under the terms of the LGPL License ver.  2.1
   with the exceptions stated in file LICENSE.
   Original code  removed or replaced  is enclosed between (*--  and --*)
   markers;  new code  is  identified by  (*++ and  ++*)  markers, or  by
   {i {b BreadCaml Note} ... } in OCamldoc comments.
   ---------------------------------------------------------------------- *)
EOF
)

TITLE[4]="OCamlclean (CeCILL -> GPL v2)"
FIND[4]='-name "*.ml" -o -name "*.mli"'
HEADER[4]=$(cat <<EOF
(* ----------------------------------------------------------------------
   $SIGNATURE
                                     SOFTWARE DI TERZI/3RD PARTY SOFTWARE
   OCamlclean
     Origine/Source: https://github.com/bvaugon/ocamlclean
     Copyright (C) 2015 Benoît Vaugon
     Integrazione in BreadCaml/Integration into BreadCaml:
     $DATE $AUTHOR

   Questo file  è distribuito nei  termini della licenza CeCILL  (si veda
   CeCILL-LICENSE-fr, in francese, oppure CeCILL-LICENSE-en, in inglese),
   il cui art. 5.3.4 ne  consente l'integrazione nel Progetto BreadCaml e
   la sua ridistribuzione sotto licenza GNU GPL.

   This file  is distributed under the  terms of the CeCILL  License (see
   CeCILL-LICENSE-fr,  in  French  language,  and  CeCILL-LICENSE-en,  in
   English). Article  5.3.4 of that  license allows its  integration into
   The BreadCaml Project and its redistribution under the GNU GPL.
   ---------------------------------------------------------------------- *)
EOF
)

####

if (( $# == 0 )); then
    # nessun argomento: stampa i modelli disponibili.
    print_templates
    exit 0
elif (( $# > 1 )); then
    echo "$0: troppi argomenti." 1>&2
    echo "Usa '$0 --help' per informazioni." 1>&2
    exit 1
elif [[ $1 == "-help" || $1 == "--help" ]]; then
    help
    exit 0
elif [[ ! -d $1 ]]; then
    echo "$0: la cartella '$1' non esiste." 1>&2
    exit 1
fi

DIR="$1"

# Attende dall'utente una scelta valida
ask_user
until [[ $CHOICE == 0 || ( $CHOICE =~ ^[0-9]+ && -n ${TITLE[$CHOICE]} ) ]]; do
    read -p "Scelta non valida, riprova (^C per uscire): " CHOICE 
done

if [[ $CHOICE == 0 ]]; then
    echo "Rimuovo gli header da tutti i file in '$(pwd)' e nelle subdirectory,"
    read -p "CONFERMI? (s/n) " CONFIRM
    if [[ $CONFIRM =~ [sS] ]]; then
	remove_all_headers
    else
	echo "Rimozione annullata".
    fi
else
    echo "Applicazione di ${TITLE[$CHOICE]}..."
    # Usa eval per evitare l'espansione di * in FIND.
    eval "find \"\$DIR\" -type f \( ${FIND[$CHOICE]} \)"|while read -r FILE; do
	add_header "$FILE" "$CHOICE"
    done
    echo "Operazione completata!"
fi
