#!/bin/bash

# -----------------------------------------------------------------------
# Progetto BreadCaml / The BreadCaml Project
# Copyright (C) 2026 Piero Furiesi
#
# Questo  programma  è  software  libero; può  essere  ridistribuito  e/o
# modificato nei termini della GNU  General Public License (GPL) versione
# 2; si veda il file LICENZA-it nella cartella radice del progetto.
#
# This program is free software; you can redistribute it and/or modify it
# under the terms  of the GNU General Public License  (GPL) version 2, as
# specified in the LICENSE-en file in the project root folder.
# -----------------------------------------------------------------------

if [[ "$1" = "--help" || "$1" = "-h" || -n "$2" ]]; then
    cat <<EOF
$0 [DIRECTORY]
Aggiunge gli header appropriati a tutti i file sorgenti OCaml o ACME
nella DIRECTORY indicata e nelle sue subdirectory.
Se DIRECTORY non è indicata, stampa i modelli di header disponibili.
EOF
    exit 0
fi

# Definizione degli header

DATE="21-Apr-2026"
SIGNATURE="Progetto BreadCaml / The BreadCaml Project"
AUTHOR="Piero Furiesi"

TITLE[1]="Sorgenti OCaml - no terze parti (GPL v2)"
FIND[1]='-name "*.ml" -o -name "*.mli" -o -name "*.ml.tpl"'
HEADER[1]=$(cat <<EOF
(* ----------------------------------------------------------------------
   $SIGNATURE
   Copyright (C) $DATE $AUTHOR

   Questo  programma  è software  libero;  può  essere ridistribuito  e/o
   modificato nei termini della GNU General Public License (GPL) versione
   2; si veda il file LICENZA-it nella cartella radice del progetto.

   This program is  free software; you can redistribute  it and/or modify
   it under the terms of the  GNU General Public License (GPL) version 2,
   as specified in the LICENSE-en file in the project root folder.
   ---------------------------------------------------------------------- *)
EOF
)

TITLE[2]="Sorgenti ACME - no terze parti (GPL v2)"
FIND[2]='-name "*.asm"'
HEADER[2]=$(cat <<EOF
;; ----------------------------------------------------------------------
;; $SIGNATURE
;; Copyright (C) $DATE $AUTHOR
;;
;; Questo  programma  è software  libero;  può  essere ridistribuito  e/o
;; modificato nei termini della GNU General Public License (GPL) versione
;; 2; si veda il file LICENZA-it nella cartella radice del progetto.
;;
;; This program is  free software; you can redistribute  it and/or modify
;; it under the terms of the  GNU General Public License (GPL) version 2,
;; as specified in the LICENSE-en file in the project root folder.
;; ----------------------------------------------------------------------
EOF
)

TITLE[3]="StdLib di OCaml modificata (LGPL v2.1 + Eccezione)"
FIND[3]='-name "*.ml" -o -name "*.mli"'
HEADER[3]=$(cat <<EOF
(* ----------------------------------------------------------------------
   $SIGNATURE
                                     SOFTWARE DI TERZI/3RD PARTY SOFTWARE
   OCaml Standard Library
     Origine/Source: https://ocaml.org
     Copyright (C) 1996 Institut National de Recherche en Informatique et
     en Automatique
     Modifiche/Modifications: $DATE $AUTHOR

   Questo file è distribuito nei termini  della licenza LGPL ver. 2.1 con
   le eccezioni riportate nel file LICENSE (in inglese).
   Il codice originale rimosso o sostituito è incluso tra (*-- e --*); le
   aggiunte sono  identificate da  (*++ e ++*)  oppure, nei  commenti per
   OCamldoc, da {i {b BreadCaml Note} ... }.

   This file is distributed under the terms of the LGPL License ver.  2.1
   with the exceptions stated in file LICENSE.
   Original code  removed or replaced  is enclosed between (*--  and --*)
   markers;  new code  is  identified by  (*++ and  ++*)  markers, or  by
   {i {b BreadCaml Note} ... } in OCamldoc comments.
   ---------------------------------------------------------------------- *)
EOF
)

TITLE[4]="OCamlclean (CeCILL -> GPL v2)"
FIND[4]='-name "*.ml" -o -name "*.mli"'
HEADER[4]=$(cat <<EOF
(* ----------------------------------------------------------------------
   $SIGNATURE
                                     SOFTWARE DI TERZI/3RD PARTY SOFTWARE
   OCamlclean
     Origine/Source: https://github.com/bvaugon/ocamlclean
     Copyright (C) 2015 Benoît Vaugon
     Integrazione in BreadCaml/Integration into BreadCaml:
     $DATE $AUTHOR

   Questo file  è distribuito nei  termini della licenza CeCILL  (si veda
   CeCILL-LICENSE-fr, in francese, oppure CeCILL-LICENSE-en, in inglese),
   il cui art. 5.3.4 ne  consente l'integrazione nel Progetto BreadCaml e
   la sua ridistribuzione sotto licenza GNU GPL.

   This file  is distributed under the  terms of the CeCILL  License (see
   CeCILL-LICENSE-fr,  in  French  language,  and  CeCILL-LICENSE-en,  in
   English). Article  5.3.4 of that  license allows its  integration into
   The BreadCaml Project and its redistribution under the GNU GPL.
   ---------------------------------------------------------------------- *)
EOF
)

# Se non è stata passata una cartella come argomento, stampa i modelli
# disponibili; altrimenti controlla che la cartella esista
if [[ -z $1 ]]; then
    for I in ${!TITLE[@]}; do
	echo ""
	echo "vvv $I) ${TITLE[$I]}"
	echo "${HEADER[$I]}"
	echo "^^^ $I) FINE MODELLO"
	echo ""
    done | less
    exit 0
elif [[ ! -d $1 ]]; then
    echo "Errore: La cartella '$1' non esiste."
    exit 1
fi

DIR="$1"

# Selezione dell'header
echo "Quale header vuoi applicare ai file in '$DIR'?"
for I in ${!TITLE[@]}; do
    echo " $I) ${TITLE[$I]}"
done
read -p "Scegli un'opzione (1 ... ${#TITLE[@]}): " CHOICE

# Assegna lo header scelto
if [[ $CHOICE =~ ^[0-9]+ && -n ${TITLE[$CHOICE]} ]]; then
    echo "Applicazione di ${TITLE[$CHOICE]}..."
else
    echo "Scelta non valida. Uscita."
    exit 1
fi

# Trova tutti i file da elaborare nella directory e nelle sue subdirectory
# Usa eval per evitare l'espansione di * in FIND
eval "find \"\$DIR\" -type f \( ${FIND[$CHOICE]} \)" | while read -r FILE; do
    # Salta il file se nelle prime tre righe contiene già la firma
    if grep -q -m 3 "$SIGNATURE" "$FILE"; then
        echo "Saltato (header già presente): $FILE"
    else
        TEMP_FILE=$(mktemp)
        echo "${HEADER[$CHOICE]}" > "$TEMP_FILE"
        echo "" >> "$TEMP_FILE"		# Riga vuota di separazione
        cat "$FILE" >> "$TEMP_FILE"
        mv "$TEMP_FILE" "$FILE"
        echo "Header inserito in: $FILE"
    fi
done

echo "Operazione completata!"
