#!/bin/bash

# depends.asm generator for src/asm/stdlib_*.asm routines

# CODING RULES for stdlib_*.asm files to let this script work:

# 1) Each routine MUST have this structure:
#       <IFDEF><ROUTINE_LABEL> {
#       <ROUTINE_LABEL>
#           asm code...
#       }
#    where  <LABEL_PART>    ::= [[:alpha:]](_?[[:alnum:]])*
#           <IFDEF>         ::= ^[ \t]*!ifdef[ \t]+caml_PRIM__
#           <ROUTINE_LABEL> ::= caml_<LABEL_PART>
#    The final '}' must be at 1st column; any '}' in asm code must not.

# 2) Other global labels in asm code MUST match this regex:
#           <GLOBAL_LABEL>  ::= <ROUTINE_LABEL>__<LABEL_PART>
#    (note the two underscore characters.)

# 3) All charachters from the LEFTMOST ';' to end of line will be treated as
#    comments and discarded, also if the semicolon is quoted by ' or ":
#           LDA #';':JSR caml_my_great_routine      ;BAD!
#
#           LDA #';'                                ;GOOD!
#           JSR caml_my_great_routine

# 4) The unique exception to rule 3) is a comment as
#           ;FALLTHROUGH caml_following_routine
#    which is treated as a dependency.
#    All fallthroughs MUST be commented as above! (Case-insensitive)

PWD="$(pwd)"
[[ ${PWD%/src/asm} == $PWD ]] && { echo "Not in 'src/asm'!"; exit 1; }

# Input and output files
INFILE=stdlib_*.asm
OUTFILE=depends.asm

# sed program to extract deps
LBLPART='[[:alpha:]](_?[[:alnum:]])*'
IFDEF='^[ \t]*!ifdef[ \t]+caml_PRIM__'
ROUTINE="caml_$LBLPART"
COMMENT=';.*$'
FALLTHROUGH=';+[ \t]*fallthrough[ \t]+'
SEDPROGRAM="
  /$IFDEF/, /^}/ {
  /$IFDEF/ {                            # First line:
    s/$IFDEF($ROUTINE).*$/\1 \"/        #  isolate routine name and add '"'
    h                                   #  copy to hold space
    d                                   #  delete, start next cycle
  }
  /^}/ {                                # Last line:
    g                                   #  get held text; then add '"'
    a \"
    p                                   #  print: routine '"' dep dep... '"'
    d                                   #  delete, start next cycle
  }
                                        # Lines in between:
  s/^.*$FALLTHROUGH($ROUTINE).*$/ \1/i  #  extract dep from fallthrough comment
  s/$COMMENT//g                         #  remove other ACME comments
  s/.*($ROUTINE)(__$LBLPART)?/§\1/g     #  prepend § to each dep
  /§/! d                                #  no deps: delete, start next cycle
  s/[^§]*§($ROUTINE)[^§]*/\1 /g         #  remove § and text between deps
  H                                     #  append deps to hold space
}"

# Init DEPS array
declare -A DEPS="($(sed -s -n -E "$SEDPROGRAM" $INFILE))"

# Remove self deps and fake deps (any caml_xyz which is not a routine)
for ROUTINE in ${!DEPS[@]}; do
    DEPLIST=''
    for DEP in ${DEPS["$ROUTINE"]}; do
	# ${VAR+string} expands to string if VAR is set, to '' if unset
	[[ $DEP != $ROUTINE && ${DEPS[$DEP]+x} ]] && DEPLIST+="$DEP "
    done
    DEPS["$ROUTINE"]="$DEPLIST"
done

# Calculate the transitive closure of all deps (breadth-first visit)
declare -A TRCLOS
declare -Ai VISITED
declare -a QUEUE
for ROUTINE in ${!DEPS[@]}; do
    VISITED=()
    QUEUE=()
    QHEAD=0
    for DEP in ${DEPS["$ROUTINE"]}; do
	VISITED["$DEP"]=1
	QUEUE+=("$DEP")
    done
    while (( QHEAD < ${#QUEUE[@]} )); do
	NODE="${QUEUE[$QHEAD]}"
	(( QHEAD++ ))
	for DEP in ${DEPS["$NODE"]}; do
	    if ! (( ${VISITED[$DEP]} )); then
		VISITED["$DEP"]=1
		QUEUE+=("$DEP")
	    fi
	done
    done
    TRCLOS["$ROUTINE"]=$(printf "%s\n" ${!VISITED[@]})
done

# Generate the output file
{   echo ";; AUTO-GENERATED FILE - DO NOT EDIT"
    echo ";; Generated $(date -u -Iseconds) by $0"
    echo ""
    for ROUTINE in $(printf "%s\n" ${!DEPS[@]}|sort); do
	[[ ${TRCLOS[$ROUTINE]} ]] && {
            echo "!ifdef caml_PRIM__$ROUTINE {"
            for DEP in $(printf "%s\n" ${TRCLOS[$ROUTINE]}|sort); do
		echo "  !set caml_PRIM__$DEP=1"
            done
            echo "}"
            echo ""
	}
    done
} > "$OUTFILE"
