#!/bin/bash

# depends.asm generator for src/asm/stdlib_*.asm routines

# Input and output files
OUTFILE="$1"
shift
INFILE="$@"

# CODING RULES for stdlib_*.asm files to let this script work:
#
# 1) Each routine MUST have this structure:
#
#       !ifdef caml_PRIM__<ROUTINE_LABEL(i)> '{'
#       <ROUTINE_LABEL(i)>
#           acme_code
#       [<GLOBAL_LABEL(i,1)> ['=' acme_expr]]
#           acme_code
#           ...
#       [<GLOBAL_LABEL(i,n)> ['=' acme_expr]]
#           acme_code
#           [; fallthrough <ROUTINE_LABEL(i+1)>]
#       '}'
#
#  · <ROUTINE_LABEL(x)> is the string "caml_", followed by a sequence of
#    alphanumeric strings, separated by "_"; the first string of the sequence
#    must start with a letter.
#
#  · <GLOBAL_LABEL(i,x)> is the <ROUTINE_LABEL(i)>, followed by "__" and a
#    sequence of alphanumeric strings, separated by "_"; the first string of
#    the sequence must start with a letter.
#
#  · Both acme_code and acme_expr may obviously contain references to other
#    <ROUTINE_LABEL(j)> and/or <GLOBAL_LABEL(j)>s, which will be treated
#    as dependencies of <ROUTINE_LABEL(i)> on <ROUTINE_LABEL(j)>.
#
#  · A fallthrough point MUST be commented by one or more ';', followed by
#    optional spaces/tabs, the case-insensitive string "fallthrough", one or
#    more spaces/tabs, and finally the <ROUTINE_LABEL(i+1)>; the comment will
#    be treated as a dependency of <ROUTINE_LABEL(i)> on <ROUTINE_LABEL(i+1)>;
#    the comment MUST precede the final closing brace '}'.
#
#  · The final closing brace '}' MUST be in the FIRST column; no other '}' in
#    acme_code may appear in the first column.
#
# 2) All charachters from the LEFTMOST ';' to the end of line will be treated
#    as comments and DISCARDED by this script (except "; fallthrough..."),
#    even if the semicolon is enclosed in single- or double-quote characters:
#    .BAD:  LDA #';':JSR caml_my_routine   ;this dep will be discarded
#    .GOOD: LDA #';'
#           JSR caml_my_routine            ;this dep will be caught

# sed program to extract deps
SEQ='[a-zA-Z](_?[a-zA-Z0-9])*'
ROUT="caml_$SEQ"
IFDEF='^[ \t]*!ifdef[ \t]+caml_PRIM__'
FALLTH='^[^;]*;+[ \t]*fallthrough[ \t]+'
SEDPROGRAM="
  /$IFDEF/, /^}/ {
  /$IFDEF/ {                   # First line:
    s/$IFDEF($ROUT).*$/\1 \"/  #  isolate the routine name, add quote
    h                          #  copy the line to the hold space
    d                          #  delete it and start next cycle
  }
  /^}/ {                       # Last line:
    g                          #  get the whole held text; add quote
    a \"
    p                          #  print routine name followed by deps
    d                          #  delete all and start next cycle
  }
                               # Lines in between:
  s/$FALLTH($ROUT).*$/ \1/i    #  extract dep from fallthrough comment
  s/;.*$//g                    #  remove other ACME comments
  s/.*($ROUT)(__$SEQ)?/§\1/g   #  prepend § to each dep
  /§/! d                       #  if no deps, delete and start next cycle
  s/[^§]*§($ROUT)[^§]*/\1 /g   #  remove § and text between deps
  H                            #  append deps to the hold space
}"

# Init DEPS array
declare -A DEPS="($(sed -s -n -E "$SEDPROGRAM" $INFILE))"

# Remove self deps and fake deps (any caml_xyz which is not a routine)
for ROUTINE in ${!DEPS[@]}; do
    DEPLIST=''
    for DEP in ${DEPS["$ROUTINE"]}; do
	# ${VAR+string} expands to string if VAR is set, to '' if unset
	[[ $DEP != $ROUTINE && ${DEPS[$DEP]+x} ]] && DEPLIST+="$DEP "
    done
    DEPS["$ROUTINE"]="$DEPLIST"
done

# Calculate the transitive closure of all deps (breadth-first visit)
declare -A TRCLOS
declare -Ai VISITED
declare -a QUEUE
for ROUTINE in ${!DEPS[@]}; do
    VISITED=()
    QUEUE=()
    QHEAD=0
    for DEP in ${DEPS["$ROUTINE"]}; do
	VISITED["$DEP"]=1
	QUEUE+=("$DEP")
    done
    while (( QHEAD < ${#QUEUE[@]} )); do
	NODE="${QUEUE[$QHEAD]}"
	(( QHEAD++ ))
	for DEP in ${DEPS["$NODE"]}; do
	    if ! (( ${VISITED[$DEP]} )); then
		VISITED["$DEP"]=1
		QUEUE+=("$DEP")
	    fi
	done
    done
    TRCLOS["$ROUTINE"]=$(printf "%s\n" ${!VISITED[@]})
done

# Generate the output file
{   echo ";; AUTO-GENERATED FILE - DO NOT EDIT"
    echo ";; Generated $(date -Iseconds) by $0"
    echo ""
    for ROUTINE in $(printf "%s\n" ${!DEPS[@]}|sort); do
	[[ ${TRCLOS[$ROUTINE]} ]] && {
            echo "!ifdef caml_PRIM__$ROUTINE {"
            for DEP in $(printf "%s\n" ${TRCLOS[$ROUTINE]}|sort); do
		echo "  !set caml_PRIM__$DEP=1"
            done
            echo "}"
            echo ""
	}
    done
} > "$OUTFILE"
